// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ChartJS")>]
[<assembly: AssemblyProductAttribute("ChartJS")>]
[<assembly: AssemblyDescriptionAttribute("Visualisation for Jupyter notebooks with Chart.js")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ChartJS"
    let [<Literal>] AssemblyProduct = "ChartJS"
    let [<Literal>] AssemblyDescription = "Visualisation for Jupyter notebooks with Chart.js"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
